<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\chdb\chdb.csproj" Condition="'$(PUSH_TOOL)' != 'true'" />
    <!-- when packing the tool for publishing, depend on the published chdb package;
         the native library is resolved via its runtime.json -->
    <PackageReference Include="chdb" Version="$(Version)" Condition="'$(PUSH_TOOL)' == 'true'" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>chdb</ToolCommandName>
    <PackageId>chdb-tool</PackageId>
    <!-- <PackageId Condition="$(IsLinuxX64) == true">chdb-tool-linux-x64</PackageId>
    <PackageId Condition="$(IsLinuxArm64) == true">chdb-tool-linux-arm64</PackageId>
    <PackageId Condition="$(IsOsxX64) == true">chdb-tool-osx-x64</PackageId>
    <PackageId Condition="$(IsOsxArm64) == true">chdb-tool-osx-arm64</PackageId> -->
    <Title>chdb tool</Title>
    <Description>clickhouse local cli as a dotnet tool</Description>
  </PropertyGroup>
</Project>
